CREATE DATABASE IF NOT EXISTS meteo

USE 'meteo'

CREATE TABLE METEO_DATA  (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    temperature FLOAT(4, 2),
    humidity TINYINT ,
    create_date DATETIME NOT NULL
);
