USE `dimkonko$meteo`;

DROP TABLE IF EXISTS `METEO_DATA`;

CREATE TABLE METEO_DATA (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    temperature TINYINT,
    humidity TINYINT,
    create_date DATETIME NOT NULL
);
